### ISSUE TITLE
Error: invalid literal for int() with base 10: '0.0109'

### ISSUE THREAD

**Issue by dktanwar** [morrislab/qapa#26] opened 2019-10-01 14:39 UTC
```bash
qapa build --db ensembl_identifiers.txt -g gencode.polyA_sites.bed -p atlas.clusters.mm10.2-0.bed gencode.basic.txt > output_utrs.bed
```
```
[qapa] Version 1.2.3
[qapa] Extracting 3' UTRs from table
/home/ubuntu/.local/lib/python2.7/site-packages/qapa-1.2.3-py2.7.egg/qapa/extract.py:131: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  conn = pd.read_table(args.db)
/home/ubuntu/.local/lib/python2.7/site-packages/qapa-1.2.3-py2.7.egg/qapa/extract.py:170: Warning: Skipping ENSMUST00000096862.4 as chromosome chr1_GL456210_random contains underscores.
  Warning)
/home/ubuntu/.local/lib/python2.7/site-packages/qapa-1.2.3-py2.7.egg/qapa/extract.py:170: Warning: Skipping ENSMUST00000177562.1 as chromosome chr1_GL456210_random contains underscores.
  Warning)
/home/ubuntu/.local/lib/python2.7/site-packages/qapa-1.2.3-py2.7.egg/qapa/extract.py:170: Warning: Skipping ENSMUST00000111364.2 as chromosome chr1_GL456210_random contains underscores.
  Warning)
/home/ubuntu/.local/lib/python2.7/site-packages/qapa-1.2.3-py2.7.egg/qapa/extract.py:170: Warning: Skipping ENSMUST00000115931.2 as chromosome chr1_GL456210_random contains underscores.
  Warning)
/home/ubuntu/.local/lib/python2.7/site-packages/qapa-1.2.3-py2.7.egg/qapa/extract.py:170: Warning: Skipping ENSMUST00000115928.2 as chromosome chr1_GL456210_random contains underscores.
  Warning)
/home/ubuntu/.local/lib/python2.7/site-packages/qapa-1.2.3-py2.7.egg/qapa/extract.py:170: Warning: Skipping ENSMUST00000179211.1 as chromosome chr1_GL456211_random contains underscores.
  Warning)
/home/ubuntu/.local/lib/python2.7/site-packages/qapa-1.2.3-py2.7.egg/qapa/extract.py:170: Warning: Skipping ENSMUST00000179124.1 as chromosome chr1_GL456211_random contains underscores.
  Warning)
/home/ubuntu/.local/lib/python2.7/site-packages/qapa-1.2.3-py2.7.egg/qapa/extract.py:170: Warning: Skipping ENSMUST00000179890.1 as chromosome chr1_GL456211_random contains underscores.
  Warning)
/home/ubuntu/.local/lib/python2.7/site-packages/qapa-1.2.3-py2.7.egg/qapa/extract.py:170: Warning: Skipping ENSMUST00000178603.1 as chromosome chr1_GL456211_random contains underscores.
  Warning)
/home/ubuntu/.local/lib/python2.7/site-packages/qapa-1.2.3-py2.7.egg/qapa/extract.py:166: Warning: Suppressing chromosome warnings...
  warnings.warn("Suppressing chromosome warnings...", Warning)
[qapa] Annotating 3' UTRs
[qapa] Error: invalid literal for int() with base 10: '0.0109'
[qapa] Finished!
```

**Comment by kcha** [comment] 2019-10-02 03:14
Thanks for posting this error. This issue is a duplicate of #22 and is now addressed in version 1.3.0.

**Closed by kcha** 2019-10-02 03:14 UTC
